name: iOS-Swift_xcodegen
configs:
  Debug: debug
  Test: debug
  TestCI: debug
  Release: release
projectReferences:
  Sentry:
    path: ../../Sentry.xcodeproj
fileGroups:
  - ../Shared/Config
  - project.yml
options:
  bundleIdPrefix: io.sentry
targets:
  iOS-Swift:
    type: application
    platform: iOS
    sources:
      - iOS-Swift
      - ../Shared/GitInjections.swift
      - ../Shared/screenshot.png
      - ../Shared/SampleAssets.xcassets
    dependencies:
      - target: Sentry/Sentry
    configFiles:
      Debug: iOS-Swift.xcconfig
      Release: iOS-Swift.xcconfig
      Test: iOS-Swift.xcconfig
      TestCI: iOS-Swift.xcconfig
    postCompileScripts:
      - script: ../Shared/inject-git-info.sh
        name: Inject Git Information into Info.plist
        basedOnDependencyAnalysis: false
    postBuildScripts:
      - script: ../Shared/reset-git-info.sh
        name: Reset Git Fields in Info.plist
        basedOnDependencyAnalysis: false
  iOS-Swift-UITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - iOS-Swift-UITests
    configFiles:
      Debug: iOS-Swift-UITests.xcconfig
      Release: iOS-Swift-UITests.xcconfig
      Test: iOS-Swift-UITests.xcconfig
      TestCI: iOS-Swift-UITests.xcconfig
