name: UI Tests
on:
  push:
    branches:
      - main

  pull_request:
    paths:
      - "Sources/**"
      - "Tests/**"
      - ".github/workflows/ui-tests.yml"
      - "fastlane/**"
      - ".sauce/config.yml"
      - "scripts/ci-select-xcode.sh"
      - "Samples/iOS-Swift/**"
      - "**/*.xctestplan"

# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ui-tests-macos:
    name: UI Tests for macOS-Swift
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: ./scripts/ci-select-xcode.sh "16.2"

      - name: Run Fastlane
        run: bundle exec fastlane ui_tests_macos_swift

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@cf701569b05ccdd861a76b8607a66d76f6fd4857 # v5.5.1
        if: always()
        with:
          report_paths: "build/reports/junit.xml"
          fail_on_failure: true
          fail_on_parse_error: true
          detailed_summary: true

      - name: Upload Result Bundle
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: ui-tests-macos-swift.xcresult
          path: fastlane/test_results/ui-tests-macos-swift.xcresult

      - name: Archiving Raw Test Logs
        uses: actions/upload-artifact@v4
        if: ${{ failure() || cancelled() }}
        with:
          name: ui-tests-macos-swift-raw-output
          path: |
            ~/Library/Logs/scan/*.log
            ./fastlane/test_output/**
